# This is the main idea of the yaml file
steps: 
- name: 'gcr.io/cloud-builders/docker'
  id: Build Docker Image
  args:
  - 'build'
  - '.'
  - '-t'
  - 'gcr.io/$PROJECT_ID/team-api-tests:latest'

  